export const SET_TOCKEN = "auth/SET_TOCKEN"
export const GET_TOCKEN = "auth/GET_TOCKEN"
export const REFRESH_TOCKEN = "auth/REFRESH_TOCKEN"
export const GET_USER = "auth/GET_USER"
export const LOG_IN = "auth/LOG_IN"
export const SET_IS_LOG_IN = "auth/SET_IS_LOG_IN"
